In [1]:
import numpy as np

### 1. Create a 3x3 NumPy array with random integers between 1 and 100. Then, interchange its rows and columns.

In [2]:
arr = np.random.randint(1, 101, size = (3, 3))
arr = arr.T
print(arr)

[[49 80  4]
 [76 41 38]
 [25 72 17]]


### 2. Generate a 1D NumPy array with 10 elements. Reshape it into a 2x5 array, then into a 5x2 array

In [3]:
arr = np.random.randint(1, 101, size=10)
arr1 = arr.reshape(2, 5)
arr2 = arr.reshape(5, 2)
print(arr1)
print()
print(arr2)

[[95 23 54 89  5]
 [28 18 70 87 74]]

[[95 23]
 [54 89]
 [ 5 28]
 [18 70]
 [87 74]]


### 3. Create a 4x4 NumPy array with random float values. Add a border of zeros around it, resulting in a 6x6 array.

In [4]:
random_array = np.random.rand(4, 4)

padded_array = np.pad(random_array, pad_width=1, mode='constant', constant_values=0)

print("Original 4x4 array with random float values:\n", random_array)
print("\n6x6 array with a border of zeros:\n", padded_array)


Original 4x4 array with random float values:
 [[0.40705143 0.18661917 0.49782437 0.41995923]
 [0.66462858 0.19679427 0.53068653 0.52387227]
 [0.15458642 0.93344781 0.25605821 0.42162907]
 [0.7885353  0.08133249 0.43683582 0.02399359]]

6x6 array with a border of zeros:
 [[0.         0.         0.         0.         0.         0.        ]
 [0.         0.40705143 0.18661917 0.49782437 0.41995923 0.        ]
 [0.         0.66462858 0.19679427 0.53068653 0.52387227 0.        ]
 [0.         0.15458642 0.93344781 0.25605821 0.42162907 0.        ]
 [0.         0.7885353  0.08133249 0.43683582 0.02399359 0.        ]
 [0.         0.         0.         0.         0.         0.        ]]


### 4. Using NumPy, create an array of integers from 10 to 60 with a step of 5.

In [5]:
arr = np.arange(10, 61, 5)
print(arr)

[10 15 20 25 30 35 40 45 50 55 60]


### 5. Create a NumPy array of strings ['python', 'numpy', 'pandas']. Apply different case transformations (uppercase, lowercase, title case, etc.) to each element.

In [6]:
arr = np.array(['python', 'numpy', 'pandas'])

uppercase_arr = np.char.upper(arr)
lowercase_arr = np.char.lower(arr)
titlecase_arr = np.char.title(arr)
capitalize_arr = np.char.capitalize(arr)
swapcase_arr = np.char.swapcase(arr)

print("Original array:", arr)
print("Uppercase:", uppercase_arr)
print("Lowercase:", lowercase_arr)
print("Title case:", titlecase_arr)
print("Capitalize:", capitalize_arr)
print("Swap case:", swapcase_arr)

Original array: ['python' 'numpy' 'pandas']
Uppercase: ['PYTHON' 'NUMPY' 'PANDAS']
Lowercase: ['python' 'numpy' 'pandas']
Title case: ['Python' 'Numpy' 'Pandas']
Capitalize: ['Python' 'Numpy' 'Pandas']
Swap case: ['PYTHON' 'NUMPY' 'PANDAS']


### 6. Generate a NumPy array of words. Insert a space between each character of every word in the array.

In [7]:
words = np.array(['python', 'numpy', 'pandas'])

vectorized_insert_spaces = np.vectorize(lambda word: ' '.join(word))

spaced_words = vectorized_insert_spaces(words)

print("Original array:", words)
print("Array with spaces between characters:", spaced_words)

Original array: ['python' 'numpy' 'pandas']
Array with spaces between characters: ['p y t h o n' 'n u m p y' 'p a n d a s']


### 7. Create two 2D NumPy arrays and perform element-wise addition, subtraction, multiplication, and division.

In [8]:
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

addition = array1 + array2
subtraction = array1 - array2
multiplication = array1 * array2
division = array1 / array2

print("Array 1:")
print(array1)
print("\nArray 2:")
print(array2)

print("\nElement-wise addition:")
print(addition)
print("\nElement-wise subtraction:")
print(subtraction)
print("\nElement-wise multiplication:")
print(multiplication)
print("\nElement-wise division:")
print(division)

Array 1:
[[1 2 3]
 [4 5 6]]

Array 2:
[[ 7  8  9]
 [10 11 12]]

Element-wise addition:
[[ 8 10 12]
 [14 16 18]]

Element-wise subtraction:
[[-6 -6 -6]
 [-6 -6 -6]]

Element-wise multiplication:
[[ 7 16 27]
 [40 55 72]]

Element-wise division:
[[0.14285714 0.25       0.33333333]
 [0.4        0.45454545 0.5       ]]


### 8. Use NumPy to create a 5x5 identity matrix, then extract its diagonal elements.

In [9]:
identity_matrix = np.eye(5, dtype=int)

diagonal_elements = np.diag(identity_matrix)

print("5x5 Identity Matrix:")
print(identity_matrix)
print("\nDiagonal Elements:")
print(diagonal_elements)

5x5 Identity Matrix:
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

Diagonal Elements:
[1 1 1 1 1]


### 9. Generate a NumPy array of 100 random integers between 0 and 1000. Find and display all prime numbers in this array.

In [10]:
random_array = np.random.randint(0, 1000, size=100)

def is_prime(n):
    if n <= 1:
        return False
    for i in range(2, int(np.sqrt(n)) + 1):
        if n % i == 0:
            return False
    return True

prime_numbers = np.array([num for num in random_array if is_prime(num)])

print("Random array of 100 integers between 0 and 1000:")
print(random_array)
print("\nPrime numbers in the array:")
print(prime_numbers)


Random array of 100 integers between 0 and 1000:
[855 713 230 239 427 192 807 125 793 663 452 726 840 665 268 246 568 707
 542 288 536 773 311 582 680  86 394 136 881 240 558 140 280  98 791 458
 141 310 520 397 975 509 502 649 781  99 574 717 902 625 299 887  11 246
 321 694 302 498 549 778 913 345 694 167 133   8 987 440   2 390 792 736
 442 938 735 774 714   7 915 914 952 289 164 318 139 377  46 908 767  88
  22 247 636 995 393 446  31 304 328  25]

Prime numbers in the array:
[239 773 311 881 397 509 887  11 167   2   7 139  31]


### 10. Create a NumPy array representing daily temperatures for a month. Calculate and display the weekly averages.

In [11]:
#Assuming temperature is between 20 to 34
daily_temperatures = np.random.randint(20, 35, size=30)

num_weeks = len(daily_temperatures) // 7

weekly_temperatures = daily_temperatures[:num_weeks*7].reshape(num_weeks, 7)
weekly_averages = np.mean(weekly_temperatures, axis=1)

print("Daily temperatures for the month:")
print(daily_temperatures)
print("\nWeekly temperatures (7 days per week):")
print(weekly_temperatures)
print("\nWeekly averages:")
print(weekly_averages)

remaining_days = daily_temperatures[num_weeks*7:]
if remaining_days.size > 0:
    print("\nTemperatures for remaining days:")
    print(remaining_days)

Daily temperatures for the month:
[22 22 29 30 32 30 21 26 23 30 30 31 32 30 28 26 20 20 25 21 26 33 24 28
 24 20 22 30 27 22]

Weekly temperatures (7 days per week):
[[22 22 29 30 32 30 21]
 [26 23 30 30 31 32 30]
 [28 26 20 20 25 21 26]
 [33 24 28 24 20 22 30]]

Weekly averages:
[26.57142857 28.85714286 23.71428571 25.85714286]

Temperatures for remaining days:
[27 22]
